"""add signal table

Revision ID: 029a863da1e3
Revises: 708d965e76ca
Create Date: 2026-05-18 13:12:21.360008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029a863da1e3'
down_revision: Union[str, None] = '708d965e76ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.String(length=500), nullable=True),
    sa.Column('ai_severity', sa.String(length=20), nullable=True),
    sa.Column('ai_category', sa.String(length=30), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_rationale', sa.Text(), nullable=True),
    sa.Column('ai_recommends_promotion', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('crisis_id', sa.String(length=36), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crisis_id'], ['crisis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_source'), 'signal', ['source'], unique=False)
    op.create_index(op.f('ix_signal_status'), 'signal', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_status'), table_name='signal')
    op.drop_index(op.f('ix_signal_source'), table_name='signal')
    op.drop_table('signal')
    # ### end Alembic commands ###
