"""p2 simulation continuity media legal hold tables

Revision ID: 187d0dc82125
Revises: 2ffe0f8ef9a7
Create Date: 2026-05-19 11:45:41.562640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187d0dc82125'
down_revision: Union[str, None] = '2ffe0f8ef9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scenario_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('generated_scenario', sa.Text(), nullable=True),
    sa.Column('generated_actions', sa.JSON(), nullable=False),
    sa.Column('expected_outcomes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('evaluation_summary', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('evaluation_breakdown', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_scenario_type'), 'simulation', ['scenario_type'], unique=False)
    op.create_index(op.f('ix_simulation_status'), 'simulation', ['status'], unique=False)
    op.create_table('continuity_activation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crisis_id', sa.String(length=36), nullable=False),
    sa.Column('bcp_plan_id', sa.String(length=120), nullable=True),
    sa.Column('bcp_plan_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('response_payload', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crisis_id'], ['crisis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_continuity_activation_crisis_id'), 'continuity_activation', ['crisis_id'], unique=False)
    op.create_index(op.f('ix_continuity_activation_status'), 'continuity_activation', ['status'], unique=False)
    op.create_table('legal_hold',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crisis_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('custodians', sa.JSON(), nullable=False),
    sa.Column('data_sources', sa.JSON(), nullable=False),
    sa.Column('hold_notice_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.String(length=255), nullable=True),
    sa.Column('release_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crisis_id'], ['crisis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_hold_crisis_id'), 'legal_hold', ['crisis_id'], unique=False)
    op.create_index(op.f('ix_legal_hold_status'), 'legal_hold', ['status'], unique=False)
    op.create_table('media_mention',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('outlet', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('key_themes', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('crisis_id', sa.String(length=36), nullable=True),
    sa.Column('mentioned_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crisis_id'], ['crisis.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_mention_crisis_id'), 'media_mention', ['crisis_id'], unique=False)
    op.create_index(op.f('ix_media_mention_mentioned_at'), 'media_mention', ['mentioned_at'], unique=False)
    op.create_index(op.f('ix_media_mention_outlet'), 'media_mention', ['outlet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_mention_outlet'), table_name='media_mention')
    op.drop_index(op.f('ix_media_mention_mentioned_at'), table_name='media_mention')
    op.drop_index(op.f('ix_media_mention_crisis_id'), table_name='media_mention')
    op.drop_table('media_mention')
    op.drop_index(op.f('ix_legal_hold_status'), table_name='legal_hold')
    op.drop_index(op.f('ix_legal_hold_crisis_id'), table_name='legal_hold')
    op.drop_table('legal_hold')
    op.drop_index(op.f('ix_continuity_activation_status'), table_name='continuity_activation')
    op.drop_index(op.f('ix_continuity_activation_crisis_id'), table_name='continuity_activation')
    op.drop_table('continuity_activation')
    op.drop_index(op.f('ix_simulation_status'), table_name='simulation')
    op.drop_index(op.f('ix_simulation_scenario_type'), table_name='simulation')
    op.drop_table('simulation')
    # ### end Alembic commands ###
