"""communication delivery and sentiment fields

Revision ID: 2ffe0f8ef9a7
Revises: 70498e4bab6a
Create Date: 2026-05-18 17:05:04.105674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ffe0f8ef9a7'
down_revision: Union[str, None] = '70498e4bab6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add columns with server defaults so existing rows backfill cleanly; then
    # drop the server default to keep the model definition authoritative.
    op.add_column('communication', sa.Column('delivery_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('communication', sa.Column('sent_at', sa.DateTime(), nullable=True))
    op.add_column('communication', sa.Column('delivery_log', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('communication', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('communication', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.add_column('communication', sa.Column('sentiment_analyzed_at', sa.DateTime(), nullable=True))
    op.add_column('communication', sa.Column('predicted_reaction', sa.Text(), nullable=True))
    op.add_column('communication', sa.Column('risk_flags', sa.JSON(), nullable=False, server_default='[]'))
    op.create_index(op.f('ix_communication_delivery_status'), 'communication', ['delivery_status'], unique=False)
    op.alter_column('communication', 'delivery_status', server_default=None)
    op.alter_column('communication', 'delivery_log', server_default=None)
    op.alter_column('communication', 'risk_flags', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_delivery_status'), table_name='communication')
    op.drop_column('communication', 'risk_flags')
    op.drop_column('communication', 'predicted_reaction')
    op.drop_column('communication', 'sentiment_analyzed_at')
    op.drop_column('communication', 'sentiment_score')
    op.drop_column('communication', 'sentiment')
    op.drop_column('communication', 'delivery_log')
    op.drop_column('communication', 'sent_at')
    op.drop_column('communication', 'delivery_status')
    # ### end Alembic commands ###
